// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbn5cL1Ts-4Lk8YFTkDMAHIU0WSO7q6T0',
    appId: '1:189946807753:web:c5d49eeeba9ab8a51ed418',
    messagingSenderId: '189946807753',
    projectId: 'our-access-456403-v4',
    authDomain: 'our-access-456403-v4.firebaseapp.com',
    storageBucket: 'our-access-456403-v4.firebasestorage.app',
    measurementId: 'G-3EFVXZGE6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAghwygVfGHmL0hCEos6kUs7mmCVGpv0lY',
    appId: '1:189946807753:android:9919e068241e48471ed418',
    messagingSenderId: '189946807753',
    projectId: 'our-access-456403-v4',
    storageBucket: 'our-access-456403-v4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd42KF0BZgR6vsXHp8mKqv9moT5ut2-YQ',
    appId: '1:189946807753:ios:f384fd60276f8c441ed418',
    messagingSenderId: '189946807753',
    projectId: 'our-access-456403-v4',
    storageBucket: 'our-access-456403-v4.firebasestorage.app',
    iosBundleId: 'com.example.voxtaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd42KF0BZgR6vsXHp8mKqv9moT5ut2-YQ',
    appId: '1:189946807753:ios:f384fd60276f8c441ed418',
    messagingSenderId: '189946807753',
    projectId: 'our-access-456403-v4',
    storageBucket: 'our-access-456403-v4.firebasestorage.app',
    iosBundleId: 'com.example.voxtaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbn5cL1Ts-4Lk8YFTkDMAHIU0WSO7q6T0',
    appId: '1:189946807753:web:2514d602d1f566791ed418',
    messagingSenderId: '189946807753',
    projectId: 'our-access-456403-v4',
    authDomain: 'our-access-456403-v4.firebaseapp.com',
    storageBucket: 'our-access-456403-v4.firebasestorage.app',
    measurementId: 'G-HPY5SH6W2B',
  );

}